//------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18010
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------------------------------------

namespace ShoppingList.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShoppingList.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à return.
        /// </summary>
        public static string AboutPopup_AppBar_Return {
            get {
                return ResourceManager.GetString("AboutPopup_AppBar_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AppChallenge.
        /// </summary>
        public static string AboutPopup_Button_AppChallenge {
            get {
                return ResourceManager.GetString("AboutPopup_Button_AppChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give my opinion.
        /// </summary>
        public static string AboutPopup_Button_Review {
            get {
                return ResourceManager.GetString("AboutPopup_Button_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version {0}.
        /// </summary>
        public static string AboutPopup_Button_Version {
            get {
                return ResourceManager.GetString("AboutPopup_Button_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ABOUT SHOPPING LIST.
        /// </summary>
        public static string AboutPopup_Title {
            get {
                return ResourceManager.GetString("AboutPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This item is already in your favorites..
        /// </summary>
        public static string AddArticlePopup_AddToFavorite_Error {
            get {
                return ResourceManager.GetString("AddArticlePopup_AddToFavorite_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the name of the item.
        /// </summary>
        public static string AddArticlePopup_ArticleControl_Label {
            get {
                return ResourceManager.GetString("AddArticlePopup_ArticleControl_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add.
        /// </summary>
        public static string AddArticlePopup_Button_Add {
            get {
                return ResourceManager.GetString("AddArticlePopup_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cancel.
        /// </summary>
        public static string AddArticlePopup_Button_Cancel {
            get {
                return ResourceManager.GetString("AddArticlePopup_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the quantity.
        /// </summary>
        public static string AddArticlePopup_QuantityControl_Label {
            get {
                return ResourceManager.GetString("AddArticlePopup_QuantityControl_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Article to buy.
        /// </summary>
        public static string AddArticlePopup_SubTitle_ToBuy {
            get {
                return ResourceManager.GetString("AddArticlePopup_SubTitle_ToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Article in favorite.
        /// </summary>
        public static string AddArticlePopup_SubTitle_ToFavorite {
            get {
                return ResourceManager.GetString("AddArticlePopup_SubTitle_ToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MY COURSES.
        /// </summary>
        public static string AddArticlePopup_Title_ToBuy {
            get {
                return ResourceManager.GetString("AddArticlePopup_Title_ToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FAVORITES.
        /// </summary>
        public static string AddArticlePopup_Title_ToFavorite {
            get {
                return ResourceManager.GetString("AddArticlePopup_Title_ToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SHOPPING LIST.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à about....
        /// </summary>
        public static string HoemForm_AppBarMenu_About {
            get {
                return ResourceManager.GetString("HoemForm_AppBarMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add items to buy here.
        /// </summary>
        public static string HoemForm_FirstPivot_SubTitle {
            get {
                return ResourceManager.GetString("HoemForm_FirstPivot_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à find here your favorite articles.
        /// </summary>
        public static string HoemForm_SecondPivot_SubTitle {
            get {
                return ResourceManager.GetString("HoemForm_SecondPivot_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add a favorite.
        /// </summary>
        public static string HomeForm_AppBar_AddFavory {
            get {
                return ResourceManager.GetString("HomeForm_AppBar_AddFavory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add item.
        /// </summary>
        public static string HomeForm_AppBar_AddShopping {
            get {
                return ResourceManager.GetString("HomeForm_AppBar_AddShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à store selection.
        /// </summary>
        public static string HomeForm_AppBar_ValidShopping {
            get {
                return ResourceManager.GetString("HomeForm_AppBar_ValidShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à my courses.
        /// </summary>
        public static string HomeForm_FirstPivot_Title {
            get {
                return ResourceManager.GetString("HomeForm_FirstPivot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To access the gallery, disconnect your phone from the computer..
        /// </summary>
        public static string HomeForm_Gallery_Message {
            get {
                return ResourceManager.GetString("HomeForm_Gallery_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantity : {0}.
        /// </summary>
        public static string HomeForm_Item_Quantity {
            get {
                return ResourceManager.GetString("HomeForm_Item_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total quantity purchased : {0}.
        /// </summary>
        public static string HomeForm_Item_QuantityTotal {
            get {
                return ResourceManager.GetString("HomeForm_Item_QuantityTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à upload a photo (gallery).
        /// </summary>
        public static string HomeForm_ItemMenu_FromGallery {
            get {
                return ResourceManager.GetString("HomeForm_ItemMenu_FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à take a photo.
        /// </summary>
        public static string HomeForm_ItemMenu_Photo {
            get {
                return ResourceManager.GetString("HomeForm_ItemMenu_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à remove items to buy.
        /// </summary>
        public static string HomeForm_ItemMenu_Remove {
            get {
                return ResourceManager.GetString("HomeForm_ItemMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à remove from favorites.
        /// </summary>
        public static string HomeForm_ItemMenu_RemoveFavorite {
            get {
                return ResourceManager.GetString("HomeForm_ItemMenu_RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à delete the photo.
        /// </summary>
        public static string HomeForm_ItemMenu_RemovePhoto {
            get {
                return ResourceManager.GetString("HomeForm_ItemMenu_RemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add to favorites.
        /// </summary>
        public static string HomeForm_ItemMenu_ToFavorite {
            get {
                return ResourceManager.GetString("HomeForm_ItemMenu_ToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To access the gallery, disconnect your phone from the computer..
        /// </summary>
        public static string HomeForm_Photo_Message {
            get {
                return ResourceManager.GetString("HomeForm_Photo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Article:.
        /// </summary>
        public static string HomeForm_RemoveItem_Title {
            get {
                return ResourceManager.GetString("HomeForm_RemoveItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You enjoy using ShoppingList?.
        /// </summary>
        public static string HomeForm_Review_FirstLine {
            get {
                return ResourceManager.GetString("HomeForm_Review_FirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Take a second to evaluate. Thank you :).
        /// </summary>
        public static string HomeForm_Review_SecondLine {
            get {
                return ResourceManager.GetString("HomeForm_Review_SecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Review ShoppingList.
        /// </summary>
        public static string HomeForm_Review_Title {
            get {
                return ResourceManager.GetString("HomeForm_Review_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à favorites.
        /// </summary>
        public static string HomeForm_SecondPivot_Title {
            get {
                return ResourceManager.GetString("HomeForm_SecondPivot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You confirm that the selected items are in your basket? Selected papers will be removed from the list..
        /// </summary>
        public static string HomeForm_Validation_Message {
            get {
                return ResourceManager.GetString("HomeForm_Validation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My basket.
        /// </summary>
        public static string HomeForm_Validation_Title {
            get {
                return ResourceManager.GetString("HomeForm_Validation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à loading....
        /// </summary>
        public static string SplashScreenForm_Loading_Label {
            get {
                return ResourceManager.GetString("SplashScreenForm_Loading_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à version {0}.{1}.{2}.
        /// </summary>
        public static string SplashScreenForm_Version_Label {
            get {
                return ResourceManager.GetString("SplashScreenForm_Version_Label", resourceCulture);
            }
        }
    }
}
